baseURL = 'https://example.org/'
languageCode = 'en-US'
theme = 'simple_learn'
title = 'Learn.henri.run'


[markup.goldmark.renderHooks.link]
enableDefault = true

[markup.goldmark.renderer]
unsafe = true
