baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'


[module]

[module.hugoVersion]
extended = false
min = '0.146.0'


[build]
[[build.cachebusters]]
source = '(postcss|tailwind)\.config\.js'
target = 'css'

